#!/bin/sh
#
# idiot detector
test X = X
if [ $? = 0 ]; then cat <<EOF

This file contains ^M characters at the end of each line.
If this is because you got the .zip version of the distribution,
you should go back and get the .tar.Z or .tar.gz version, or use
the unzip option that translates CR LF to LF.

EOF
    exit 1;
fi;


### Make sure PATH contains every plausible location of 'make'.
PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/usr/ucb:/usr/local:/usr/lbin:/etc:/usr/new:/usr/new/bin:/usr/nbin:/usr/ccs/bin"
export PATH

MAKE=${MAKE-make}
export MAKE
${MAKE} -f unix/Makefile `egrep '^TFVER=' src/vars.mak` MAKE="${MAKE}" $*
