/* config.h
 * This file was manually generated by A.Sahlbach for os/2
 */

#define PLATFORM_OS2
#define HAVE_DRIVES

#define UNAME      "OS/2"
#define MAILDIR    ""

#define UNISTD_H <unistd.h>
#define STDLIB_H <stdlib.h>
#define LOCALE_H <locale.h>
#define STRING_H <string.h>
#define MEMORY_H <memory.h>
#define NETINET_IN_H <netinet/in.h>
#define ARPA_INET_H <arpa/inet.h>
#define NETDB_H <netdb.h>
#undef  HAVE_PWD_H
#define HAVE_STDARG
#define CASE_OK
#define RETSIG void
#define TIME_T time_t

#undef  HAVE_bcopy
#define HAVE_bsearch
#undef  HAVE_bzero
#define HAVE_fileno
#define HAVE_getcwd
#define HAVE_gethostbyname
#undef  HAVE_getpwnam
#undef  HAVE_getwd
#define HAVE_h_errno
#undef  HAVE_hstrerror	/* Not all versions of OS/2 have hstrerror. -Ken Keys */
#undef  HAVE_index
#define HAVE_kill
#define HAVE_memcpy
#define HAVE_memset
#define HAVE_raise
#define HAVE_setlocale
#define HAVE_sigaction
#define HAVE_srand
#undef  HAVE_srandom
#undef  HAVE_strcasecmp
#define HAVE_strchr
#undef  HAVE_strcmpi
#define HAVE_strcspn
#define HAVE_strerror
#define HAVE_strftime
#define HAVE_stricmp
#define HAVE_strstr
#define HAVE_strtod
#define HAVE_strtol
#define HAVE_tzset


#define TERMCAP
#define USE_TERMIOS

/* LIBDIR is defined by os2make.cmd */
